/*
 * This source file was generated by the Gradle 'init' task
 */
package tcalc;

import java.util.Scanner;

import expressionParser.Parser;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Scanner scan = new Scanner(System.in);
        System.out.println("enter an expression. \n    ");
        String input = scan.nextLine();


        Parser parser = new Parser(input);

        double res = parser.evaluate();

        System.out.println("The result is: " + res);

        scan.close();
    }
}
