/*
 * This source file was generated by the Gradle 'init' task
 */
package tcalc;

import java.util.Scanner;

import expressionParser.Parser;

import expressionParser.ExpressionTree;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Scanner scan = new Scanner(System.in);
        System.out.println("enter an expression. \n    ");
        String input = scan.nextLine();

        double res = stackImplementation(input);

        System.out.println("The result is: " + res);
        scan.close();
    }

    public static double stackImplementation(String input) {

        Parser parser = new Parser(input);

        return parser.evaluate();
    }

    public static double treeImplementation(String input) {
        ExpressionTree tree = new ExpressionTree();

        tree.buildExpressionTree(input);

        // Evaluate the expression
        return tree.evaluateExpressionTree(tree.root);
    }
}
